config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :omniauth_callbacks => "omniauth_callbacks" ,
    :sessions           => "users/sessions",
    :registrations      => "users/registrations",
    :passwords          => "users/passwords"
  }

  root 'toppages#index'
  get 'toppages/show'

  namespace :admin do
    resources :users
    resources :owners
    resources :shops
  end

  namespace :owner do
    resources :users
    resources :shops
  end

  resources :shops, :only => [:show]
  get '/areashops/:area' => 'shops#index', as: 'areashops'

  post 'like/:shop_id'     => 'likes#like', as: 'like'
  delete 'unlike/:shop_id' => 'likes#unlike', as: 'unlike'
  get 'nologin' => 'likes#nologin'
  get 'all_likes_destroy' => 'likes#all_likes_destroy'

  resources :messagerooms

  resources :messages

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  #オーナーに属する
  belongs_to :owner
  #likesを持つ
  has_many :likes, dependent: :destroy
  #ショップイメージ
  has_many :shopimages, inverse_of: :shop, dependent: :destroy
  accepts_nested_attributes_for :shopimages, allow_destroy: true
  #メニューイメージ
  has_many :menuimages, inverse_of: :shop, dependent: :destroy
  accepts_nested_attributes_for :menuimages, allow_destroy: true
  #メッセージ
  has_many :messagerooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  #メインイメージ
  mount_uploader :image1, ImageUploader
  geocoded_by :address
  after_validation :geocode
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < AdminController
    before_action :set_shop, only: [:edit, :update, :destroy]

    def index
        @shop = Shop.includes(:owner).all
        @current_owner = Owner.find_by(user_id: current_user )
    end

    def new
        @shop = Shop.new
    end

    def edit
    end

    def create
        @shop = Shop.new(shop_params)
        respond_to do |format|
            if @shop.save
                format.html { redirect_to admin_shops_path, notice: 'Shop was successfully created.' }
                format.json { render :show, status: :created, location: @shop }
            else
                format.html { render :new }
                format.json { render json: @shop.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
          if @shop.update(shop_params)
            format.html { redirect_to admin_shops_path, notice: 'Shop was successfully changeed.' }
            format.json { render :show, status: :ok, location: @shop }
          else
            format.html { render :edit }
            format.json { render json: @shop.errors, status: :unprocessable_entity }
          end
        end
    end

    def destroy
        @shop.destroy
        respond_to do |format|
          format.html { redirect_to admin_shops_path, notice: 'Shop was successfully destroyed.' }
          format.json { head :no_content }
        end
    end


    private

    def set_shop
        @shop = Shop.find(params[:id])
    end

    #params name      string  名前
    #params area      string  所属エリア
    #params address   string  住所
    #params email     string  メール
    #params tel       integer 電話
    #params url       string  url
    #params image1    string  メインイメージ
    def shop_params
      params.require(:shop).permit(:name, :area, :address, :email, :tel, :url, :image1)
    end

end

app/controllers/owner/shops_controller.rb
class Owner::ShopsController < ApplicationController
    before_action :set_shop, only: [:edit, :update, :destroy]

    def index
        @current_owner = Owner.find_by(user_id: current_user )
        #現在のオーナーの保有するショップ一覧を取得
        @shop = Shop.where(owner_id: @current_owner.id )
        #@TODO 並び替え Likeカウントの順番
        #@have_ranking=Have.group(:item_id).limit(10).order('count_item_id DESC').count('item_id')
    end

    def new
        @shop = Shop.new
        @shop.shopimages.build
        @shop.menuimages.build
        @current_owner = Owner.find_by(user_id: current_user )
        #binding.pry
    end

    def create
        @shop = Shop.new(shop_params)
        respond_to do |format|
            if @shop.save
                format.html { redirect_to owner_shops_path, notice: 'Shop was successfully created.' }
                format.json { render :show, status: :created, location: @shop }
            else
                format.html { render :new }
                format.json { render json: @shop.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
          if @shop.update(shop_params)
            format.html { redirect_to owner_shops_path, notice: 'Shop was successfully changeed.' }
            format.json { render :show, status: :ok, location: @shop }
          else
            format.html { render :edit }
            format.json { render json: @shop.errors, status: :unprocessable_entity }
          end
        end
    end

    def destroy
        @shop.destroy
        respond_to do |format|
          format.html { redirect_to owner_shops_path, notice: 'Shop was successfully destroyed.' }
          format.json { head :no_content }
        end
    end

    private

    def set_shop
        @shop = Shop.find(params[:id])
    end

    #params name          string  ショップ名
    #params area          string  所属エリア @TODO integerに変更
    #params postal_code1  integer 郵便番号1 ex)110
    #params postal_code2  integer 郵便番号2 ex)0083
    #params address       string  住所
    #params email         string  メール
    #tel                  integer 電話
    #url                  string  url
    #image1               integer メインイメージ
    #owner_id             integer オーナーid
    def shop_params
      params.require(:shop).permit(:name, :area, :postal_code1, :postal_code2, :address, :email, :tel, :url, :image1, :owner_id, shopimages_attributes: [:shop_id, :image, :remove_image], menuimages_attributes: [:shop_id, :image, :remove_image])
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
    before_action :set_current_owner, only: [:index, :show]

    def index
        @area = params[:area]
        #エリアに該当するショップ一覧を取得
        @shops = Shop.where(:area => @area)
    end

    def show
        @shop = Shop.find(params[:id])
        @message = Message.new
        @messageroom = Messageroom.new
        @messageroom.messages.build
    end

    private

    def set_current_owner
        @current_owner = Owner.find_by(user_id: current_user )
    end

end

app/views/shops/_like.html.erb
<%= link_to image_tag("heart365.png"),
    like_path(shop.id),
    :class => "like-#{shop.id} btn-like btn",
    remote: :true,
    method: :post %>

app/views/shops/_shop_infowin.html.erb
<%= shop.name %>
<span class="infowin_img">
    <%= image_tag(shop.image1) %>
</span>

app/views/shops/_unlike.html.erb
<%= link_to image_tag("heart118.png"),
    unlike_path(shop.id),
    :class => "like-#{shop.id} btn-like btn",
    remote: :true,
    method: :delete %>

app/views/shops/index.html.erb
<!-- areashops -->
<div class="breadcrumbs">
    <ul>
        <li><%= link_to 'HOME', root_path %></li>
        <li>></li>
        <li><%= @area %></li>
    </ul>
</div>

<div class="container">
    <div class="areashops_top clearfix grid">
        <% if @shops.present? %>
            <% @shops.each do |shop| %>
                <figure class="shop">
                    <%= link_to (image_tag(shop.image1_url)), shop_path(shop.id) %>
                    <figcaption class="area_shop_name">
                        <span class="shop_name"><%= shop.name %></span>
                    </figcaption>
                </figure>
            <% end %>
        <% else %>
            エリアの登録はありません。
        <% end %>
    </div>
</div>

<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 400px;'></div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {scrollwheel: false}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw googlemap(@shops).to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(15);
    });
</script>

app/views/shops/show.html.erb
<div class="breadcrumbs">
    <ul>
        <li><%= link_to 'HOME', root_path %></li>
        <li>></li>
        <li><%= link_to @shop.area, areashops_path(@shop.area) %></li>
        <li>></li>
        <li><%= @shop.name %></li>
    </ul>
</div>

<div class="container">
    <%#= @messageroom.messages %>
    <div class="detailshop_top clearfix grid">
        <figure class="detail_shop">
            <%= image_tag (@shop.image1_url) %>
        </figure>
        <div class="shop_info">
            <ul>
                <li><%= @shop.name %></li>
                <li><%= @shop.address %></li>
                <li><%= @shop.tel %></li>
                <li><%= link_to "#{@shop.url}(test To yahoo!)", "http://www.yahoo.co.jp/", target: "_blank" %></li>
            </ul>
        </div>
      <div class="shop_like_show">
        <div class="likes_set">
            <% if user_signed_in? %>
                <% if current_user.likes.find_by(shop_id: @shop.id) %>
                    <span class="like_btn">
                        <%= render 'shops/unlike', shop: @shop %>
                    </span>
                <% else %>
                    <span class="like_btn">
                        <%= render 'shops/like', shop: @shop %>
                    </span>
                <% end %>
            <% else %>
                <span class="like_btn"><%= link_to image_tag("heart365.png"), nologin_path %></span>
            <% end %>
            <span class="like_nums like_num_<%= @shop.id %>">
                <%= @shop.likes.count %>
            </span>
        </div>
      </div>

      <%= form_for((@messageroom), :html => { method: :post, multipart: true }) do |f| %>
        <form>
          <div class="form-group">
            <div class="">
              <% stamp = Time.now.to_i %>
              <%= fields_for "messageroom[messages_attributes][#{stamp}]" do |ff| %>
                <%= ff.text_area :content, id: "message_#{stamp}", class: "form-control" %>
                <% if user_signed_in? %>
                  <%= ff.hidden_field :user_id, :value => @current_user.id %>
                <% end %>
              <% end %>
            </div>
          </div>
          <% if user_signed_in? %>
            <%= f.hidden_field :user_id, :value => @current_user.id %>
            <%= f.hidden_field :shop_id, :value => @shop.id %>
            <div class="msg_btn">
              <%= f.submit "メッセージ送信", class: 'btn btn-primary btn-md' %>
            </div>
          <% else %>
            <span class="btn btn-primary btn-md nologin msg_btn">
              <%= link_to "メッセージ送信", nologin_path %>
            </span>
          <% end %>
        </form>
      <% end %>
    </div>
</div>
<!---SEARCH END----->
<div id="select_tab">
    <ul class="nav nav-tabs" style="margin-bottom: -1.5px;">
        <li class="active"><a href="#tab1" data-toggle="tab">ATOMS</a></li>
        <li><a href="#tab2" data-toggle="tab">FOOD&DRINK</a></li>
    </ul>
</div>
<!--TAB START-->

<!--TAB START-->
<div id="myTabContent" class="tab-content" style="padding-top: 50px;border-top: 1px #eee solid;">
    <!--TAB ATOMS START-->
    <div class="tab-pane fade in active" id="tab1">
        <div class="container">
            <p class="">Atoms</p>
            <div id="" class="top_shops clearfix grid">
                <% @shop.shopimages.each do |i| %>
                    <% unless i.image.blank? %>
                        <figure class="shop_atoms">
                            <%= image_tag i.image %>
                        </figure>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
    <!--TAB ATOMS END-->
    <!--TAB FOOD DRINK START-->
    <div class="tab-pane fade" id="tab2">
        <div class="container">
            <p class="">Food & Drink</p>
            <div id="" class="top_shops clearfix grid">
                <% @shop.menuimages.each do |i| %>
                    <% unless i.image.blank? %>
                        <figure class="shop_menus">
                            <%= image_tag i.image %>
                        </figure>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
    <!--TAB FOOD DRINK END-->
</div>
<!-- TAB END -->

<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 400px;'></div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {scrollwheel: false}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw googlemap(@shop).to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(17);
    });
</script>