config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :omniauth_callbacks => "omniauth_callbacks" ,
    :sessions           => "users/sessions",
    :registrations      => "users/registrations",
    :passwords          => "users/passwords"
  }

  root 'toppages#index'
  get 'toppages/show'

  namespace :admin do
    resources :users
    resources :owners
    resources :shops
  end

  namespace :owner do
    resources :users
    resources :shops
  end

  resources :shops, :only => [:show]
  get '/areashops/:area' => 'shops#index', as: 'areashops'

  post 'like/:shop_id'     => 'likes#like', as: 'like'
  delete 'unlike/:shop_id' => 'likes#unlike', as: 'unlike'
  get 'nologin' => 'likes#nologin'
  get 'all_likes_destroy' => 'likes#all_likes_destroy'

  resources :messagerooms

  resources :messages

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :user
  has_many :shops, dependent: :destroy

end

app/controllers/admin/owners_controller.rb
##管理者のオーナー関連のコントローラー
class Admin::OwnersController < AdminController
    before_action :set_owner, only: [:edit, :update, :destroy]

    ##編集
    #一覧表示
    def index
        @owners = Owner.all
        @current_owner = Owner.find_by(user_id: current_user )
    end

    def edit
    end
    #アップデート
    def update
        respond_to do |format|
          if @owner.update(owner_params)
            format.html { redirect_to admin_owners_path, notice: 'Owner was successfully changeed.' }
            format.json { render :show, status: :ok, location: @owner }
          else
            format.html { render :edit }
            format.json { render json: @owner.errors, status: :unprocessable_entity }
          end
        end
    end
    #消去
    def destroy
        @owner.destroy
        respond_to do |format|
            format.html { redirect_to admin_owners_path, notice: 'Owner was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    #params id オーナーid
    def set_owner
        @owner = Owner.find(params[:id])
    end

    #params last_name       string  名前
    #params first_name      string  氏名
    #params company_name    string  会社名
    #params company_address string  会社住所
    #params company_tel     integer 会社連絡先
    def owner_params
        params.require(:owner).permit(:last_name, :first_name, :company_name, :company_address, :company_tel)
    end

end

app/controllers/owner/shops_controller.rb
class Owner::ShopsController < ApplicationController
    before_action :set_shop, only: [:edit, :update, :destroy]

    def index
        @current_owner = Owner.find_by(user_id: current_user )
        #現在のオーナーの保有するショップ一覧を取得
        @shop = Shop.where(owner_id: @current_owner.id )
        #@TODO 並び替え Likeカウントの順番
        #@have_ranking=Have.group(:item_id).limit(10).order('count_item_id DESC').count('item_id')
    end

    def new
        @shop = Shop.new
        @shop.shopimages.build
        @shop.menuimages.build
        @current_owner = Owner.find_by(user_id: current_user )
        #binding.pry
    end

    def create
        @shop = Shop.new(shop_params)
        respond_to do |format|
            if @shop.save
                format.html { redirect_to owner_shops_path, notice: 'Shop was successfully created.' }
                format.json { render :show, status: :created, location: @shop }
            else
                format.html { render :new }
                format.json { render json: @shop.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
          if @shop.update(shop_params)
            format.html { redirect_to owner_shops_path, notice: 'Shop was successfully changeed.' }
            format.json { render :show, status: :ok, location: @shop }
          else
            format.html { render :edit }
            format.json { render json: @shop.errors, status: :unprocessable_entity }
          end
        end
    end

    def destroy
        @shop.destroy
        respond_to do |format|
          format.html { redirect_to owner_shops_path, notice: 'Shop was successfully destroyed.' }
          format.json { head :no_content }
        end
    end

    private

    def set_shop
        @shop = Shop.find(params[:id])
    end

    #params name          string  ショップ名
    #params area          string  所属エリア @TODO integerに変更
    #params postal_code1  integer 郵便番号1 ex)110
    #params postal_code2  integer 郵便番号2 ex)0083
    #params address       string  住所
    #params email         string  メール
    #tel                  integer 電話
    #url                  string  url
    #image1               integer メインイメージ
    #owner_id             integer オーナーid
    def shop_params
      params.require(:shop).permit(:name, :area, :postal_code1, :postal_code2, :address, :email, :tel, :url, :image1, :owner_id, shopimages_attributes: [:shop_id, :image, :remove_image], menuimages_attributes: [:shop_id, :image, :remove_image])
    end
end

app/controllers/owner/users_controller.rb
class Owner::UsersController < ApplicationController
    before_action :set_owner, only: [:edit, :update, :destroy]

    def new
        @user = User.find(current_user.id)
        @owner = Owner.new(user_id:@user.id)
    end

    def edit
        @current_owner = Owner.find_by(user_id: current_user )
    end

    def create
        @owner = Owner.new(owner_params)
        respond_to do |format|
            if @owner.save
                format.html { redirect_to root_path, notice: 'Owner was successfully created.' }
                format.json { render :show, status: :created, location: @owner }
            else
                format.html { render :new }
                format.json { render json: @owner.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
          if @owner.update(owner_params)
            format.html { redirect_to root_path, notice: 'Owner was successfully changeed.' }
            format.json { render :show, status: :ok, location: @owner }
          else
            format.html { render :edit }
            format.json { render json: @owner.errors, status: :unprocessable_entity }
          end
        end
    end

    private
    def set_owner
        @owner = Owner.find(params[:id])
    end

    #params user_id     integer ユーザid
    #params username    string  ユーザ名
    #params email       string  メール
    #params avatarurl   string  アバター
    #params password    string  パスワード@TODO
    def owner_params
        params.require(:owner).permit(:user_id, :last_name, :first_name, :company_name, :company_address, :company_tel)# :password
    end
end

app/views/admin/owners/edit.html.erb
<div class="page_title">登録オーナー情報編集</div>

<%= form_for(@owner, url: admin_owner_path(@owner), html: { method: :put }) do |f| %>
    <% if @owner.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>
            <ul>
                <% @owner.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="container form_container">
        <form class="form-horizontal">
            <div class="form-group">
                <label class="field control-label col-md-offset-2 col-md-2">
                    <%= f.label :last_name, "性" %>
                </label>
                <div class="col-md-8">
                    <%= f.text_field :last_name, autofocus: true, class: "form-control" %>
                </div>
            </div>
            <br>
            <div class="form-group">
                <label class="field control-label col-md-offset-2 col-md-2">
                    <%= f.label :first_name, "名" %>
                </label>
                <div class="col-md-8">
                    <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
                </div>
            </div>
            <br>
            <div class="form-group">
                <label class="field control-label col-md-offset-2 col-md-2">
                    <%= f.label :company_name, "会社名（屋号）" %>
                </label>
                <div class="col-md-8">
                    <%= f.text_field :company_name, class: "form-control"  %>
                </div>
            </div>
            <br>
            <div class="form-group">
                <label class="field control-label col-md-offset-2 col-md-2">
                    <%= f.label :company_address, "住所" %>
                </label>
                <div class="col-md-8">
                    <%= f.text_field :company_address, class: "form-control"  %>
                </div>
            </div>
            <br>
            <div class="form-group">
                <label class="field control-label col-md-offset-2 col-md-2">
                    <%= f.label :company_tel, "電話番号" %>
                </label>
                <div class="col-md-8">
                    <%= f.text_field :company_tel, class: "form-control"  %>
                </div>
            </div>
            <div class="actions">
                <%= f.submit "更新", class: 'btn btn-primary btn-s' %>
            </div>
            <%= link_to 'Back', admin_users_path %>
        </form>
    </div>
<% end %>

app/views/admin/owners/index.html.erb
<div class="page_title">オーナー一覧</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>No</th>
            <th>user_id</th>
            <th>性</th>
            <th>名</th>
            <th>会社名</th>
            <th>会社住所</th>
            <th>会社電話番号</th>
            <th>ショップ</th>
            <th>Edit</th>
            <th>Destroy</th>
        </tr>
    </thead>

    <tbody>
        <% @owners.each_with_index do |owner, i| %>
        <tr>
            <td><%= i+1 %></td>
            <td><%= owner.user_id %></td>
            <td><%= owner.last_name %></td>
            <td><%= owner.first_name %></td>
            <td><%= owner.company_name %></td>
            <td><%= owner.company_address %></td>
            <td><%= owner.company_tel %></td>
            <td>
            <% @ownershops = owner.shops %>
            <% @ownershops.each do |ownershop| %>
                <%= ownershop.name %>
            <% end %>
            </td>
            <td><%= link_to 'Edit', edit_admin_owner_path(owner), class: 'btn btn-warning btn-s' %></td>
            <td><%= link_to 'Destroy', admin_owner_path(owner), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-s' %></td>
        </tr>
        <% end %>
    </tbody>
</table>