config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :omniauth_callbacks => "omniauth_callbacks" ,
    :sessions           => "users/sessions",
    :registrations      => "users/registrations",
    :passwords          => "users/passwords"
  }

  root 'toppages#index'
  get 'toppages/show'

  namespace :admin do
    resources :users
    resources :owners
    resources :shops
  end

  namespace :owner do
    resources :users
    resources :shops
  end

  resources :shops, :only => [:show]
  get '/areashops/:area' => 'shops#index', as: 'areashops'

  post 'like/:shop_id'     => 'likes#like', as: 'like'
  delete 'unlike/:shop_id' => 'likes#unlike', as: 'unlike'
  get 'nologin' => 'likes#nologin'
  get 'all_likes_destroy' => 'likes#all_likes_destroy'

  resources :messagerooms

  resources :messages

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :user
  has_many :shops, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise  :database_authenticatable, :registerable,
            :recoverable, :rememberable, :trackable, :validatable,
            :timeoutable, :omniauthable

    has_many :likes, dependent: :destroy
    has_one :owner, dependent: :destroy
    has_many :messagerooms, dependent: :destroy
    has_many :messages, dependent: :destroy

    mount_uploader :avatarurl, ImageUploader

    # user, admin, owner以外をroleに追加できないようにするバリデーションを入れる。
    validates :role, inclusion: { in: %w(user admin owner) }
    #usernameの文字数制限
    validates :username, presence: true, length: { maximum: 50 }

    #findして無かったらcreate
    def self.find_or_create_from_oauth(auth)
      User.find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
        user.provider   = auth["provider"]
        user.uid        = auth["uid"]
        user.username   = auth["info"]["nickname"] || auth["info"]["name"]
        user.avatarurl  = auth["info"]["image"]
        user.email      = User.dummy_email(auth)  #@TODO ダミーメール生成
        user.password   = Devise.friendly_token[0, 20]
      end
    end

    def self.new_with_session(params, session)
        if session["devise.user_attributes"]
            new(session["devise.user_attributes"], without_protection: true) do |user|
                user.attributes = params
                user.valid?
            end
        else
            super
        end
    end

    #管理者かどうかのチェック
    def admin?
        role == 'admin'
    end
    #管理者でないかどうかのチェック
    def not_admin?
        !admin?
    end
    def owner?
        role == 'owner'
    end
    def not_owner?
        !owner?
    end
    def user?
        role == 'user'
    end
    def not_user?
        !user?
    end

    private

    #ダミーメールの生成
    def self.dummy_email(auth)
        "#{auth.uid}-#{auth.provider}@example.com"
    end

end

app/controllers/admin/owners_controller.rb
##管理者のオーナー関連のコントローラー
class Admin::OwnersController < AdminController
    before_action :set_owner, only: [:edit, :update, :destroy]

    ##編集
    #一覧表示
    def index
        @owners = Owner.all
        @current_owner = Owner.find_by(user_id: current_user )
    end

    def edit
    end
    #アップデート
    def update
        respond_to do |format|
          if @owner.update(owner_params)
            format.html { redirect_to admin_owners_path, notice: 'Owner was successfully changeed.' }
            format.json { render :show, status: :ok, location: @owner }
          else
            format.html { render :edit }
            format.json { render json: @owner.errors, status: :unprocessable_entity }
          end
        end
    end
    #消去
    def destroy
        @owner.destroy
        respond_to do |format|
            format.html { redirect_to admin_owners_path, notice: 'Owner was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    #params id オーナーid
    def set_owner
        @owner = Owner.find(params[:id])
    end

    #params last_name       string  名前
    #params first_name      string  氏名
    #params company_name    string  会社名
    #params company_address string  会社住所
    #params company_tel     integer 会社連絡先
    def owner_params
        params.require(:owner).permit(:last_name, :first_name, :company_name, :company_address, :company_tel)
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
    before_action :set_user, only: [:edit, :update, :destroy]

    def index
        @users = User.all
        @current_owner = Owner.find_by(user_id: current_user )
    end

    def edit
    end

    def update
        respond_to do |format|
          if @user.update(user_params)
            format.html { redirect_to admin_users_path, notice: 'User was successfully changeed.' }
            format.json { render :show, status: :ok, location: @user }
          else
            format.html { render :edit }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
    end

    def destroy
        if @user.admin?
            respond_to do |format|
                format.html { redirect_to admin_users_path, notice: 'Can not delete Admin user!!' }
            end
        else
            @user.destroy
            respond_to do |format|
                format.html { redirect_to admin_users_path, notice: 'User was successfully destroyed.' }
                format.json { head :no_content }
            end
        end
    end

    private
    def set_user
        @user = User.find(params[:id])
    end

    #params username    string  ユーザ名
    #params email       string  メール
    #params avatarurl   string  アバター
    #params password    strign  パスワード@TODO
    def user_params
        params.require(:user).permit(:username, :email, :avatarurl)# :password
    end

end

app/controllers/owner/shops_controller.rb
class Owner::ShopsController < ApplicationController
    before_action :set_shop, only: [:edit, :update, :destroy]

    def index
        @current_owner = Owner.find_by(user_id: current_user )
        #現在のオーナーの保有するショップ一覧を取得
        @shop = Shop.where(owner_id: @current_owner.id )
        #@TODO 並び替え Likeカウントの順番
        #@have_ranking=Have.group(:item_id).limit(10).order('count_item_id DESC').count('item_id')
    end

    def new
        @shop = Shop.new
        @shop.shopimages.build
        @shop.menuimages.build
        @current_owner = Owner.find_by(user_id: current_user )
        #binding.pry
    end

    def create
        @shop = Shop.new(shop_params)
        respond_to do |format|
            if @shop.save
                format.html { redirect_to owner_shops_path, notice: 'Shop was successfully created.' }
                format.json { render :show, status: :created, location: @shop }
            else
                format.html { render :new }
                format.json { render json: @shop.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
          if @shop.update(shop_params)
            format.html { redirect_to owner_shops_path, notice: 'Shop was successfully changeed.' }
            format.json { render :show, status: :ok, location: @shop }
          else
            format.html { render :edit }
            format.json { render json: @shop.errors, status: :unprocessable_entity }
          end
        end
    end

    def destroy
        @shop.destroy
        respond_to do |format|
          format.html { redirect_to owner_shops_path, notice: 'Shop was successfully destroyed.' }
          format.json { head :no_content }
        end
    end

    private

    def set_shop
        @shop = Shop.find(params[:id])
    end

    #params name          string  ショップ名
    #params area          string  所属エリア @TODO integerに変更
    #params postal_code1  integer 郵便番号1 ex)110
    #params postal_code2  integer 郵便番号2 ex)0083
    #params address       string  住所
    #params email         string  メール
    #tel                  integer 電話
    #url                  string  url
    #image1               integer メインイメージ
    #owner_id             integer オーナーid
    def shop_params
      params.require(:shop).permit(:name, :area, :postal_code1, :postal_code2, :address, :email, :tel, :url, :image1, :owner_id, shopimages_attributes: [:shop_id, :image, :remove_image], menuimages_attributes: [:shop_id, :image, :remove_image])
    end
end

app/controllers/owner/users_controller.rb
class Owner::UsersController < ApplicationController
    before_action :set_owner, only: [:edit, :update, :destroy]

    def new
        @user = User.find(current_user.id)
        @owner = Owner.new(user_id:@user.id)
    end

    def edit
        @current_owner = Owner.find_by(user_id: current_user )
    end

    def create
        @owner = Owner.new(owner_params)
        respond_to do |format|
            if @owner.save
                format.html { redirect_to root_path, notice: 'Owner was successfully created.' }
                format.json { render :show, status: :created, location: @owner }
            else
                format.html { render :new }
                format.json { render json: @owner.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
          if @owner.update(owner_params)
            format.html { redirect_to root_path, notice: 'Owner was successfully changeed.' }
            format.json { render :show, status: :ok, location: @owner }
          else
            format.html { render :edit }
            format.json { render json: @owner.errors, status: :unprocessable_entity }
          end
        end
    end

    private
    def set_owner
        @owner = Owner.find(params[:id])
    end

    #params user_id     integer ユーザid
    #params username    string  ユーザ名
    #params email       string  メール
    #params avatarurl   string  アバター
    #params password    string  パスワード@TODO
    def owner_params
        params.require(:owner).permit(:user_id, :last_name, :first_name, :company_name, :company_address, :company_tel)# :password
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class   Users::RegistrationsController < Devise::RegistrationsController
    def edit
      @current_owner = Owner.find_by(user_id: current_user )
    end
    
    def update
        respond_to do |format|
          if @user.update(user_params)
            format.html { redirect_to root_path, notice: 'User was successfully updated.' }
            format.json { render :show, status: :ok, location: @user }
          else
            format.html { render :edit }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
    end
    
    private
    
    def user_params
      params.require(:user).permit(:username, :email, :avatarurl)# :password
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    def new
        super
    end
    
    def create
        super
    end
    
    def destroy
        super
        flash[:danger] = "ログアウトしました。"
    end
end

app/views/owner/users/edit.html.erb
<div class="page_title">オーナー情報編集</div>
<%= form_for(@owner, url: owner_user_path(@owner), html: { method: :put }) do |f| %>
    <% if @owner.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>
            <ul>
            <% @owner.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="container form_container">
        <form class="form-horizontal">
            <div class="form-group">
                <label class="field control-label col-md-offset-2 col-md-2">
                    <%= f.label :last_name, "性" %>
                </label>
                <div class="col-md-8">
                    <%= f.text_field :last_name, autofocus: true, class: "form-control" %>
                </div>
            </div>
            <br>
            <div class="form-group">
                <label class="field control-label col-md-offset-2 col-md-2">
                    <%= f.label :first_name, "名前" %>
                </label>
                <div class="col-md-8">
                    <%= f.text_field :first_name, class: "form-control" %>
                </div>
            </div>
            <br>
            <div class="form-group">
                <label class="field control-label col-md-offset-2 col-md-2">
                    <%= f.label :company_name, "会社名（屋号）" %>
                </label>
                <div class="col-md-8">
                    <%= f.text_field :company_name, class: "form-control" %>
                </div>
            </div>
            <br>
            <div class="form-group">
                <label class="field control-label col-md-offset-2 col-md-2">
                    <%= f.label :company_address, "住所" %>
                </label>
                <div class="col-md-8">
                    <%= f.text_field :company_address, class: "form-control" %>
                </div>
            </div>
            <br>
            <div class="form-group">
                <label class="field control-label col-md-offset-2 col-md-2">
                    <%= f.label :company_tel, "電話番号" %>
                </label>
                <div class="col-md-8">
                    <%= f.text_field :company_tel, class: "form-control" %>
                </div>
            </div>
            <br>
            <div class="actions">
                <%= f.submit "更新", class: 'btn btn-primary btn-s' %>
            </div>
        </form>
    </div>
<% end %>

<%= link_to 'Back', root_path %>

app/views/owner/users/new.html.erb
<div class="container">
    <div id="owner_regist_container">
        <div class="owner_regist_title">オーナー登録</div>
        <%= form_for(@owner, url: owner_users_path(@owner), html: { method: :post }) do |f| %>
            <% if @owner.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>
                    <ul>
                    <% @owner.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                    </ul>
                </div>
            <% end %>
              
            <div class="owner_regist_form" style="float:left;">
                <form>
                    <div class="form_repre_name">
                        <label class="field last_name_label">
                            代表者氏名
                        </label>
                        <div id="name_group">
                            <div class="form-group last_name">
                                <label class="field last_name_label">
                                    <%= f.label :last_name, "性" %>
                                </label>
                                <div class="last_name_text">
                                    <%= f.text_field :last_name, autofocus: true, class: "form-control", placeholder: "高橋" %>
                                </div>
                            </div>
                            <div class="form-group first_name">
                                <label class="field first_name_label">
                                    <%= f.label :first_name, "名" %>
                                </label>
                                <div class="first_name_text">
                                    <%= f.text_field :first_name, class: "form-control", placeholder: "康哲" %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="form-group form_company_name" style="clear:both">
                        <label class="field">
                            <%= f.label :company_name, "会社名（屋号）" %>
                        </label>
                        <div class="input_company_name">
                            <%= f.text_field :company_name, class: "form-control", placeholder: "株式会社ジーズ" %>
                        </div>
                    </div>
                    <br>
                    <!--<div class="form-group">-->
                    <!--    <label class="field">-->
                    <!--        <%#= f.label :company_address, "住所" %>-->
                    <!--    </label>-->
                    <!--    <div class="">-->
                    <!--        <%#= f.text_field :company_address, class: "form-control" %>-->
                    <!--    </div>-->
                    <!--</div>-->
                    <div class="form-group form_company_address" style="height: 80px;">
                        <label class="field">
                            <%= f.label :company_address, "住所" %>
                        </label>
                        <span id="postal_mark">
                            〒
                        </span>
                        <div class="input_companypostal_code">
                            <%= f.text_field :postal_code1, class: "form-control", placeholder: "1234567" %>
                        </div>
                        <div class="search_postal">
                            <button type="button" class="btn btn-success">住所検索</button>
                        </div>
                        <br>
                        <div class="input_companyaddress">
                            <%= f.text_field :company_address, class: "form-control", placeholder: "東京都千代田区永田町..." %>
                        </div>
                    </div>
                    <br>
                    <div class="form-group form_company_tel"  style="clear:both">
                        <label class="field">
                            <%= f.label :company_tel, "電話番号" %>
                        </label>
                        <div class="input_company_tel">
                            <%= f.text_field :company_tel, class: "form-control", placeholder: "0312345678" %>
                        </div>
                    </div>
                    <br>
                    <%= f.hidden_field :user_id, :value => @owner.user_id %>
                    <div class="company_action">
                        <%= f.submit "登録", class: 'btn btn-primary btn-s' %>
                    </div>
                </form>
            </div>
        <% end %>
    </div>
</div>

<%#= link_to 'Back', root_path %>